using Google.Cloud.Firestore;

namespace Roadie.Models
{
    /// <summary>
    ///     Discord role binding configuration.
    /// </summary>
    [FirestoreData]
    public class RoadieBindRole : BaseFirestoreModel
    {
        /// <summary>
        ///     The role's unique Discord id number.
        /// </summary>
        [FirestoreProperty]
        public ulong DiscordRoleId { get; set; }

        /// <summary>
        ///     The Discord id number for the role's containing guild.
        /// </summary>
        [FirestoreProperty]
        public ulong DiscordGuildId { get; set; }

        /// <summary>
        ///     The gumroad product id associated with this role.
        /// </summary>
        [FirestoreProperty]
        public string GumroadProductId { get; set; }

        /// <summary>
        ///     Is this role generated by Roadie.
        /// </summary>
        [FirestoreProperty]
        public bool IsManaged { get; set; }
    }
}
